services:
  cartography:
    image: ghcr.io/williamjacksn/cartography
    build: .

  neo4j:
    image: neo4j:3.5.14
    environment:
      NEO4J_AUTH: none
    volumes:
      - neo4j-data:/data
    ports:
      - 7474:7474
      - 7687:7687

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/cartography
    init: true
    volumes:
      - ./:/home/python/cartography
    working_dir: /home/python/cartography

volumes:
  neo4j-data:
