version: '3.8'

services:
  cartography:
    image: ghcr.io/williamjacksn/cartography
    build: .
    environment:
      AWS_ACCESS_KEY_ID: replace this text with your access key id
      AWS_DEFAULT_REGION: us-west-2
      AWS_SECRET_ACCESS_KEY: replace this text with you secret access key
      NEO4J_URI: bolt://neo4j:7687

  neo4j:
    image: neo4j:3.5.14
    environment:
      NEO4J_AUTH: none
    volumes:
      - neo4j-data:/data
    ports:
      - 7474:7474
      - 7687:7687

volumes:
  neo4j-data:
